"""Init_db

Revision ID: 720cd62bc7c1
Revises: b828ec0be405
Create Date: 2025-10-23 11:58:34.362549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720cd62bc7c1'
down_revision: Union[str, Sequence[str], None] = 'b828ec0be405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'insurance_policies', ['policy_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurance_policies', type_='unique')
    # ### end Alembic commands ###
