"""Init db

Revision ID: 88b6061177fe
Revises: 720cd62bc7c1
Create Date: 2025-10-23 12:04:34.795020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b6061177fe'
down_revision: Union[str, Sequence[str], None] = '720cd62bc7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insurance_policies_policy_number_key'), 'insurance_policies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('insurance_policies_policy_number_key'), 'insurance_policies', ['policy_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
