"""add unique constraint for car_id, provider, policy_number

Revision ID: 8c32f0e3719e
Revises: 88b6061177fe
Create Date: 2025-10-23 12:08:57.538011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c32f0e3719e'
down_revision: Union[str, Sequence[str], None] = '88b6061177fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_policy_per_car_provider', 'insurance_policies', ['car_id', 'provider', 'policy_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_policy_per_car_provider', 'insurance_policies', type_='unique')
    # ### end Alembic commands ###
