"""add logged_expiry_at to policies

Revision ID: a27bf779036b
Revises: b824e9cabf99
Create Date: 2025-10-23 09:33:24.667601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27bf779036b'
down_revision: Union[str, Sequence[str], None] = 'b824e9cabf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_policies', sa.Column('logged_expiry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_insurance_policies_logged_expiry_at'), 'insurance_policies', ['logged_expiry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_policies_logged_expiry_at'), table_name='insurance_policies')
    op.drop_column('insurance_policies', 'logged_expiry_at')
    # ### end Alembic commands ###
