"""init schema

Revision ID: b824e9cabf99
Revises: 541fb240578f
Create Date: 2025-10-22 13:32:01.906249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b824e9cabf99'
down_revision: Union[str, Sequence[str], None] = '541fb240578f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_claim_policy'), table_name='claims')
    op.drop_constraint(op.f('claims_policy_id_fkey'), 'claims', type_='foreignkey')
    op.drop_column('claims', 'policy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('claims_policy_id_fkey'), 'claims', 'insurance_policies', ['policy_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_claim_policy'), 'claims', ['policy_id'], unique=False)
    op.drop_column('claims', 'created_at')
    # ### end Alembic commands ###
